INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (1, 'Bình Chánh', 'Huyện', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (2, 'Bình Tân', 'Quận', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (3, 'Bình Thạnh', 'Quận', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (4, 'Cần Giờ', 'Huyện', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (5, 'Củ Chi', 'Huyện', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (6, 'Gò Vấp', 'Quận', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (7, 'Hóc Môn', 'Huyện', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (8, 'Nhà Bè', 'Huyện', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (9, 'Phú Nhuận', 'Quận', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (10, 'Quận 1', '', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (11, 'Quận 10', '', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (12, 'Quận 11', '', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (13, 'Quận 12', '', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (14, 'Quận 2', '', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (15, 'Quận 3', '', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (16, 'Quận 4', '', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (17, 'Quận 5', '', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (18, 'Quận 6', '', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (19, 'Quận 7', '', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (20, 'Quận 8', '', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (21, 'Quận 9', '', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (22, 'Tân Bình', 'Quận', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (23, 'Tân Phú', 'Quận', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (24, 'Thủ Đức', 'Quận', 1);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (25, 'Ba Đình', 'Quận', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (26, 'Ba Vì', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (27, 'Bắc Từ Liêm', 'Quận', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (28, 'Cầu Giấy', 'Quận', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (29, 'Chương Mỹ', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (30, 'Đan Phượng', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (31, 'Đông Anh', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (32, 'Đống Đa', 'Quận', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (33, 'Gia Lâm', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (34, 'Hà Đông', 'Quận', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (35, 'Hai Bà Trưng', 'Quận', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (36, 'Hoài Đức', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (37, 'Hoàn Kiếm', 'Quận', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (38, 'Hoàng Mai', 'Quận', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (39, 'Long Biên', 'Quận', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (40, 'Mê Linh', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (41, 'Mỹ Đức', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (42, 'Nam Từ Liêm', 'Quận', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (43, 'Phú Xuyên', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (44, 'Phúc Thọ', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (45, 'Quốc Oai', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (46, 'Sóc Sơn', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (47, 'Sơn Tây', 'Thị xã', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (48, 'Tây Hồ', 'Quận', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (49, 'Thạch Thất', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (50, 'Thanh Oai', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (51, 'Thanh Trì', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (52, 'Thanh Xuân', 'Quận', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (53, 'Thường Tín', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (54, 'Ứng Hòa', 'Huyện', 2);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (55, 'Cẩm Lệ', 'Quận', 3);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (56, 'Hải Châu', 'Quận', 3);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (57, 'Hòa Vang', 'Huyện', 3);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (58, 'Hoàng Sa', 'Huyện', 3);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (59, 'Liên Chiểu', 'Quận', 3);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (60, 'Ngũ Hành Sơn', 'Quận', 3);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (61, 'Sơn Trà', 'Quận', 3);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (62, 'Thanh Khê', 'Quận', 3);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (63, 'Bàu Bàng', 'Huyện', 4);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (64, 'Bến Cát', 'Thị xã', 4);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (65, 'Dầu Tiếng', 'Huyện', 4);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (66, 'Dĩ An', 'Thị xã', 4);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (67, 'Phú Giáo', 'Huyện', 4);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (68, 'Tân Uyên', 'Huyện', 4);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (69, 'Thủ Dầu Một', 'Thị xã', 4);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (70, 'Thuận An', 'Huyện', 4);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (71, 'Biên Hòa', 'Thành phố', 5);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (72, 'Cẩm Mỹ', 'Huyện', 5);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (73, 'Định Quán', 'Huyện', 5);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (74, 'Long Khánh', 'Thị xã', 5);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (75, 'Long Thành', 'Huyện', 5);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (76, 'Nhơn Trạch', 'Huyện', 5);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (77, 'Tân Phú', 'Quận', 5);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (78, 'Thống Nhất', 'Huyện', 5);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (79, 'Trảng Bom', 'Huyện', 5);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (80, 'Vĩnh Cửu', 'Huyện', 5);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (81, 'Xuân Lộc', 'Huyện', 5);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (82, 'Cam Lâm', 'Huyện', 6);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (83, 'Cam Ranh', 'Thành phố', 6);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (84, 'Diên Khánh', 'Huyện', 6);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (85, 'Khánh Sơn', 'Huyện', 6);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (86, 'Khánh Vĩnh', 'Huyện', 6);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (87, 'Nha Trang', 'Thành phố', 6);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (88, 'Ninh Hòa', 'Thị xã', 6);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (89, 'Trường Sa', 'Huyện', 6);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (90, 'Vạn Ninh', 'Huyện', 6);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (91, 'An Dương', 'Huyện', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (92, 'An Lão', 'Huyện', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (93, 'Bạch Long Vĩ', 'Huyện', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (94, 'Cát Hải', 'Huyện', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (95, 'Đồ Sơn', 'Quận', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (96, 'Dương Kinh', 'Quận', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (97, 'Hải An', 'Quận', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (98, 'Hồng Bàng', 'Quận', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (99, 'Kiến An', 'Quận', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (100, 'Kiến Thụy', 'Huyện', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (101, 'Lê Chân', 'Quận', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (102, 'Ngô Quyền', 'Quận', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (103, 'Thủy Nguyên', 'Huyện', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (104, 'Tiên Lãng', 'Huyện', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (105, 'Vĩnh Bảo', 'Huyện', 7);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (106, 'Bến Lức', 'Huyện', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (107, 'Cần Đước', 'Huyện', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (108, 'Cần Giuộc', 'Huyện', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (109, 'Châu Thành', 'Huyện', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (110, 'Đức Hòa', 'Huyện', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (111, 'Đức Huệ', 'Huyện', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (112, 'Kiến Tường', 'Thị xã', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (113, 'Mộc Hóa', 'Huyện', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (114, 'Tân An', 'Thành phố', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (115, 'Tân Hưng', 'Huyện', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (116, 'Tân Thạnh', 'Huyện', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (117, 'Tân Trụ', 'Huyện', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (118, 'Thạnh Hóa', 'Huyện', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (119, 'Thủ Thừa', 'Huyện', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (120, 'Vĩnh Hưng', 'Huyện', 8);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (121, 'Bắc Trà My', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (122, 'Đại Lộc', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (123, 'Điện Bàn', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (124, 'Đông Giang', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (125, 'Duy Xuyên', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (126, 'Hiệp Đức', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (127, 'Hội An', 'Thành phố', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (128, 'Nam Giang', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (129, 'Nam Trà My', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (130, 'Nông Sơn', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (131, 'Núi Thành', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (132, 'Phú Ninh', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (133, 'Phước Sơn', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (134, 'Quế Sơn', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (135, 'Tam Kỳ', 'Thành phố', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (136, 'Tây Giang', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (137, 'Thăng Bình', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (138, 'Tiên Phước', 'Huyện', 9);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (139, 'Bà Rịa', 'Thị xã', 10);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (140, 'Châu Đức', 'Huyện', 10);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (141, 'Côn Đảo', 'Huyện', 10);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (142, 'Đất Đỏ', 'Huyện', 10);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (143, 'Long Điền', 'Huyện', 10);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (144, 'Tân Thành', 'Huyện', 10);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (145, 'Vũng Tàu', 'Thành phố', 10);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (146, 'Xuyên Mộc', 'Huyện', 10);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (147, 'Buôn Đôn', 'Huyện', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (148, 'Buôn Hồ', 'Thị xã', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (149, 'Buôn Ma Thuột', 'Thành phố', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (150, 'Cư Kuin', 'Huyện', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (151, 'Cư M gar', 'Huyện', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (152, 'Ea H Leo', 'Huyện', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (153, 'Ea Kar', 'Huyện', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (154, 'Ea Súp', 'Huyện', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (155, 'Krông Ana', 'Huyện', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (156, 'Krông Bông', 'Huyện', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (157, 'Krông Buk', 'Huyện', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (158, 'Krông Năng', 'Huyện', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (159, 'Krông Pắc', 'Huyện', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (160, 'Lăk', 'Huyện', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (161, 'M Đrăk', 'Huyện', 11);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (162, ' Thới Lai', 'Huyện', 12);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (163, 'Bình Thủy', 'Quận', 12);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (164, 'Cái Răng', 'Quận', 12);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (165, 'Cờ Đỏ', 'Huyện', 12);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (166, 'Ninh Kiều', 'Quận', 12);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (167, 'Ô Môn', 'Quận', 12);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (168, 'Phong Điền', 'Huyện', 12);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (169, 'Thốt Nốt', 'Quận', 12);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (170, 'Vĩnh Thạnh', 'Huyện', 12);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (171, 'Bắc Bình', 'Huyện', 13);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (172, 'Đảo Phú Quý', 'Huyện', 13);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (173, 'Đức Linh', 'Huyện', 13);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (174, 'Hàm Tân', 'Huyện', 13);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (175, 'Hàm Thuận Bắc', 'Huyện', 13);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (176, 'Hàm Thuận Nam', 'Huyện', 13);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (177, 'La Gi', 'Thị xã', 13);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (178, 'Phan Thiết', 'Thành phố', 13);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (179, 'Tánh Linh', 'Huyện', 13);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (180, 'Tuy Phong', 'Huyện', 13);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (181, 'Bảo Lâm', 'Huyện', 14);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (182, 'Bảo Lộc', 'Thành phố', 14);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (183, 'Cát Tiên', 'Huyện', 14);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (184, 'Đạ Huoai', 'Huyện', 14);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (185, 'Đà Lạt', 'Thành phố', 14);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (186, 'Đạ Tẻh', 'Huyện', 14);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (187, 'Đam Rông', 'Huyện', 14);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (188, 'Di Linh', 'Huyện', 14);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (189, 'Đơn Dương', 'Huyện', 14);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (190, 'Đức Trọng', 'Huyện', 14);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (191, 'Lạc Dương', 'Huyện', 14);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (192, 'Lâm Hà', 'Huyện', 14);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (193, 'A Lưới', 'Huyện', 15);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (194, 'Huế', 'Thành phố', 15);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (195, 'Hương Thủy', 'Thị xã', 15);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (196, 'Hương Trà', 'Huyện', 15);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (197, 'Nam Đông', 'Huyện', 15);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (198, 'Phong Điền', 'Huyện', 15);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (199, 'Phú Lộc', 'Huyện', 15);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (200, 'Phú Vang', 'Huyện', 15);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (201, 'Quảng Điền', 'Huyện', 15);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (202, 'An Biên', 'Huyện', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (203, 'An Minh', 'Huyện', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (204, 'Châu Thành', 'Huyện', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (205, 'Giang Thành', 'Huyện', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (206, 'Giồng Riềng', 'Huyện', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (207, 'Gò Quao', 'Huyện', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (208, 'Hà Tiên', 'Thị xã', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (209, 'Hòn Đất', 'Huyện', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (210, 'Kiên Hải', 'Huyện', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (211, 'Kiên Lương', 'Huyện', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (212, 'Phú Quốc', 'Huyện', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (213, 'Rạch Giá', 'Thành phố', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (214, 'Tân Hiệp', 'Huyện', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (215, 'U minh Thượng', 'Huyện', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (216, 'Vĩnh Thuận', 'Huyện', 16);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (217, 'Bắc Ninh', 'Thành phố', 17);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (218, 'Gia Bình', 'Huyện', 17);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (219, 'Lương Tài', 'Huyện', 17);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (220, 'Quế Võ', 'Huyện', 17);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (221, 'Thuận Thành', 'Huyện', 17);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (222, 'Tiên Du', 'Huyện', 17);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (223, 'Từ Sơn', 'Thị xã', 17);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (224, 'Yên Phong', 'Huyện', 17);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (225, 'Ba Chẽ', 'Huyện', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (226, 'Bình Liêu', 'Huyện', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (227, 'Cẩm Phả', 'Thành phố', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (228, 'Cô Tô', 'Huyện', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (229, 'Đầm Hà', 'Huyện', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (230, 'Đông Triều', 'Huyện', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (231, 'Hạ Long', 'Thành phố', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (232, 'Hải Hà', 'Huyện', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (233, 'Hoành Bồ', 'Huyện', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (234, 'Móng Cái', 'Thành phố', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (235, 'Quảng Yên', 'Huyện', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (236, 'Tiên Yên', 'Huyện', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (237, 'Uông Bí', 'Thị xã', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (238, 'Vân Đồn', 'Huyện', 18);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (239, 'Bá Thước', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (240, 'Bỉm Sơn', 'Thị xã', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (241, 'Cẩm Thủy', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (242, 'Đông Sơn', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (243, 'Hà Trung', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (244, 'Hậu Lộc', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (245, 'Hoằng Hóa', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (246, 'Lang Chánh', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (247, 'Mường Lát', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (248, 'Nga Sơn', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (249, 'Ngọc Lặc', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (250, 'Như Thanh', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (251, 'Như Xuân', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (252, 'Nông Cống', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (253, 'Quan Hóa', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (254, 'Quan Sơn', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (255, 'Quảng Xương', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (256, 'Sầm Sơn', 'Thị xã', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (257, 'Thạch Thành', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (258, 'Thanh Hóa', 'Thành phố', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (259, 'Thiệu Hóa', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (260, 'Thọ Xuân', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (261, 'Thường Xuân', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (262, 'Tĩnh Gia', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (263, 'Triệu Sơn', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (264, 'Vĩnh Lộc', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (265, 'Yên Định', 'Huyện', 19);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (266, 'Anh Sơn', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (267, 'Con Cuông', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (268, 'Cửa Lò', 'Thị xã', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (269, 'Diễn Châu', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (270, 'Đô Lương', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (271, 'Hoàng Mai', 'Thị xã', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (272, 'Hưng Nguyên', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (273, 'Kỳ Sơn', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (274, 'Nam Đàn', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (275, 'Nghi Lộc', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (276, 'Nghĩa Đàn', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (277, 'Quế Phong', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (278, 'Quỳ Châu', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (279, 'Quỳ Hợp', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (280, 'Quỳnh Lưu', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (281, 'Tân Kỳ', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (282, 'Thái Hòa', 'Thị xã', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (283, 'Thanh Chương', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (284, 'Tương Dương', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (285, 'Vinh', 'Thành phố', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (286, 'Yên Thành', 'Huyện', 20);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (287, 'Bình Giang', 'Huyện', 21);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (288, 'Cẩm Giàng', 'Huyện', 21);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (289, 'Chí Linh', 'Thị xã', 21);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (290, 'Gia Lộc', 'Huyện', 21);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (291, 'Hải Dương', 'Thành phố', 21);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (292, 'Kim Thành', 'Huyện', 21);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (293, 'Kinh Môn', 'Huyện', 21);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (294, 'Nam Sách', 'Huyện', 21);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (295, 'Ninh Giang', 'Huyện', 21);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (296, 'Thanh Hà', 'Huyện', 21);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (297, 'Thanh Miện', 'Huyện', 21);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (298, 'Tứ Kỳ', 'Huyện', 21);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (299, 'An Khê', 'Thị xã', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (300, 'AYun Pa', 'Thị xã', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (301, 'Chư Păh', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (302, 'Chư Pưh', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (303, 'Chư Sê', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (304, 'ChưPRông', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (305, 'Đăk Đoa', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (306, 'Đăk Pơ', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (307, 'Đức Cơ', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (308, 'Ia Grai', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (309, 'Ia Pa', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (310, 'KBang', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (311, 'Kông Chro', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (312, 'Krông Pa', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (313, 'Mang Yang', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (314, 'Phú Thiện', 'Huyện', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (315, 'Plei Ku', 'Thành phố', 22);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (316, 'Bình Long', 'Thị xã', 23);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (317, 'Bù Đăng', 'Huyện', 23);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (318, 'Bù Đốp', 'Huyện', 23);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (319, 'Bù Gia Mập', 'Huyện', 23);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (320, 'Chơn Thành', 'Huyện', 23);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (321, 'Đồng Phú', 'Huyện', 23);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (322, 'Đồng Xoài', 'Thị xã', 23);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (323, 'Hớn Quản', 'Huyện', 23);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (324, 'Lộc Ninh', 'Huyện', 23);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (325, 'Phú Riềng', 'Huyện', 23);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (326, 'Phước Long', 'Thị xã', 23);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (327, 'Ân Thi', 'Huyện', 24);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (328, 'Hưng Yên', 'Thành phố', 24);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (329, 'Khoái Châu', 'Huyện', 24);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (330, 'Kim Động', 'Huyện', 24);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (331, 'Mỹ Hào', 'Huyện', 24);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (332, 'Phù Cừ', 'Huyện', 24);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (333, 'Tiên Lữ', 'Huyện', 24);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (334, 'Văn Giang', 'Huyện', 24);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (335, 'Văn Lâm', 'Huyện', 24);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (336, 'Yên Mỹ', 'Huyện', 24);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (337, 'An Lão', 'Huyện', 25);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (338, 'An Nhơn', 'Huyện', 25);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (339, 'Hoài Ân', 'Huyện', 25);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (340, 'Hoài Nhơn', 'Huyện', 25);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (341, 'Phù Cát', 'Huyện', 25);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (342, 'Phù Mỹ', 'Huyện', 25);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (343, 'Quy Nhơn', 'Thành phố', 25);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (344, 'Tây Sơn', 'Huyện', 25);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (345, 'Tuy Phước', 'Huyện', 25);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (346, 'Vân Canh', 'Huyện', 25);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (347, 'Vĩnh Thạnh', 'Huyện', 25);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (348, 'Cái Bè', 'Huyện', 26);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (349, 'Cai Lậy', 'Thị xã', 26);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (350, 'Châu Thành', 'Huyện', 26);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (351, 'Chợ Gạo', 'Huyện', 26);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (352, 'Gò Công', 'Thị xã', 26);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (353, 'Gò Công Đông', 'Huyện', 26);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (354, 'Gò Công Tây', 'Huyện', 26);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (355, 'Huyện Cai Lậy', 'Huyện', 26);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (356, 'Mỹ Tho', 'Thành phố', 26);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (357, 'Tân Phú Đông', 'Huyện', 26);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (358, 'Tân Phước', 'Huyện', 26);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (359, 'Đông Hưng', 'Huyện', 27);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (360, 'Hưng Hà', 'Huyện', 27);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (361, 'Kiến Xương', 'Huyện', 27);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (362, 'Quỳnh Phụ', 'Huyện', 27);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (363, 'Thái Bình', 'Thành phố', 27);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (364, 'Thái Thuỵ', 'Huyện', 27);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (365, 'Tiền Hải', 'Huyện', 27);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (366, 'Vũ Thư', 'Huyện', 27);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (367, 'Bắc Giang', 'Thành phố', 28);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (368, 'Hiệp Hòa', 'Huyện', 28);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (369, 'Lạng Giang', 'Huyện', 28);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (370, 'Lục Nam', 'Huyện', 28);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (371, 'Lục Ngạn', 'Huyện', 28);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (372, 'Sơn Động', 'Huyện', 28);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (373, 'Tân Yên', 'Huyện', 28);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (374, 'Việt Yên', 'Huyện', 28);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (375, 'Yên Dũng', 'Huyện', 28);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (376, 'Yên Thế', 'Huyện', 28);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (377, 'Cao Phong', 'Huyện', 29);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (378, 'Đà Bắc', 'Huyện', 29);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (379, 'Hòa Bình', 'Thành phố', 29);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (380, 'Kim Bôi', 'Huyện', 29);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (381, 'Kỳ Sơn', 'Huyện', 29);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (382, 'Lạc Sơn', 'Huyện', 29);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (383, 'Lạc Thủy', 'Huyện', 29);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (384, 'Lương Sơn', 'Huyện', 29);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (385, 'Mai Châu', 'Huyện', 29);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (386, 'Tân Lạc', 'Huyện', 29);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (387, 'Yên Thủy', 'Huyện', 29);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (388, 'An Phú', 'Huyện', 30);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (389, 'Châu Đốc', 'Thị xã', 30);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (390, 'Châu Phú', 'Huyện', 30);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (391, 'Châu Thành', 'Huyện', 30);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (392, 'Chợ Mới', 'Huyện', 30);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (393, 'Long Xuyên', 'Thành phố', 30);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (394, 'Phú Tân', 'Huyện', 30);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (395, 'Tân Châu', 'Thị xã', 30);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (396, 'Thoại Sơn', 'Huyện', 30);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (397, 'Tịnh Biên', 'Huyện', 30);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (398, 'Tri Tôn', 'Huyện', 30);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (399, 'Bình Xuyên', 'Huyện', 31);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (400, 'Lập Thạch', 'Huyện', 31);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (401, 'Phúc Yên', 'Thị xã', 31);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (402, 'Sông Lô', 'Huyện', 31);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (403, 'Tam Đảo', 'Huyện', 31);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (404, 'Tam Dương', 'Huyện', 31);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (405, 'Vĩnh Tường', 'Huyện', 31);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (406, 'Vĩnh Yên', 'Thành phố', 31);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (407, 'Yên Lạc', 'Huyện', 31);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (408, 'Bến Cầu', 'Huyện', 32);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (409, 'Châu Thành', 'Huyện', 32);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (410, 'Dương Minh Châu', 'Huyện', 32);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (411, 'Gò Dầu', 'Huyện', 32);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (412, 'Hòa Thành', 'Huyện', 32);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (413, 'Tân Biên', 'Huyện', 32);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (414, 'Tân Châu', 'Huyện', 32);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (415, 'Tây Ninh', 'Thị xã', 32);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (416, 'Trảng Bàng', 'Huyện', 32);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (417, 'Đại Từ', 'Huyện', 33);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (418, 'Định Hóa', 'Huyện', 33);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (419, 'Đồng Hỷ', 'Huyện', 33);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (420, 'Phổ Yên', 'Huyện', 33);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (421, 'Phú Bình', 'Huyện', 33);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (422, 'Phú Lương', 'Huyện', 33);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (423, 'Sông Công', 'Thị xã', 33);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (424, 'Thái Nguyên', 'Thành phố', 33);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (425, 'Võ Nhai', 'Huyện', 33);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (426, 'Bắc Hà', 'Huyện', 34);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (427, 'Bảo Thắng', 'Huyện', 34);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (428, 'Bảo Yên', 'Huyện', 34);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (429, 'Bát Xát', 'Huyện', 34);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (430, 'Lào Cai', 'Thành phố', 34);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (431, 'Mường Khương', 'Huyện', 34);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (432, 'Sa Pa', 'Huyện', 34);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (433, 'Văn Bàn', 'Huyện', 34);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (434, 'Xi Ma Cai', 'Huyện', 34);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (435, 'Giao Thủy', 'Huyện', 35);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (436, 'Hải Hậu', 'Huyện', 35);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (437, 'Mỹ Lộc', 'Huyện', 35);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (438, 'Nam Định', 'Thành phố', 35);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (439, 'Nam Trực', 'Huyện', 35);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (440, 'Nghĩa Hưng', 'Huyện', 35);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (441, 'Trực Ninh', 'Huyện', 35);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (442, 'Vụ Bản', 'Huyện', 35);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (443, 'Xuân Trường', 'Huyện', 35);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (444, 'Ý Yên', 'Huyện', 35);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (445, 'Ba Tơ', 'Huyện', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (446, 'Bình Sơn', 'Huyện', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (447, 'Đức Phổ', 'Huyện', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (448, 'Lý Sơn', 'Huyện', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (449, 'Minh Long', 'Huyện', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (450, 'Mộ Đức', 'Huyện', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (451, 'Nghĩa Hành', 'Huyện', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (452, 'Quảng Ngãi', 'Thành phố', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (453, 'Sơn Hà', 'Huyện', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (454, 'Sơn Tây', 'Huyện', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (455, 'Sơn Tịnh', 'Huyện', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (456, 'Tây Trà', 'Huyện', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (457, 'Trà Bồng', 'Huyện', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (458, 'Tư Nghĩa', 'Huyện', 36);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (459, 'Ba Tri', 'Huyện', 37);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (460, 'Bến Tre', 'Thành phố', 37);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (461, 'Bình Đại', 'Huyện', 37);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (462, 'Châu Thành', 'Huyện', 37);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (463, 'Chợ Lách', 'Huyện', 37);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (464, 'Giồng Trôm', 'Huyện', 37);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (465, 'Mỏ Cày Bắc', 'Huyện', 37);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (466, 'Mỏ Cày Nam', 'Huyện', 37);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (467, 'Thạnh Phú', 'Huyện', 37);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (468, 'Cư Jút', 'Huyện', 38);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (469, 'Dăk GLong', 'Huyện', 38);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (470, 'Dăk Mil', 'Huyện', 38);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (471, 'Dăk R Lấp', 'Huyện', 38);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (472, 'Dăk Song', 'Huyện', 38);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (473, 'Gia Nghĩa', 'Thị xã', 38);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (474, 'Krông Nô', 'Huyện', 38);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (475, 'Tuy Đức', 'Huyện', 38);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (476, 'Cà Mau', 'Thành phố', 39);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (477, 'Cái Nước', 'Huyện', 39);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (478, 'Đầm Dơi', 'Huyện', 39);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (479, 'Năm Căn', 'Huyện', 39);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (480, 'Ngọc Hiển', 'Huyện', 39);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (481, 'Phú Tân', 'Huyện', 39);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (482, 'Thới Bình', 'Huyện', 39);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (483, 'Trần Văn Thời', 'Huyện', 39);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (484, 'U Minh', 'Huyện', 39);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (485, 'Bình Minh', 'Huyện', 40);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (486, 'Bình Tân', 'Quận', 40);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (487, 'Long Hồ', 'Huyện', 40);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (488, 'Mang Thít', 'Huyện', 40);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (489, 'Tam Bình', 'Huyện', 40);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (490, 'Trà Ôn', 'Huyện', 40);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (491, 'Vĩnh Long', 'Thành phố', 40);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (492, 'Vũng Liêm', 'Huyện', 40);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (493, 'Gia Viễn', 'Huyện', 41);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (494, 'Hoa Lư', 'Huyện', 41);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (495, 'Kim Sơn', 'Huyện', 41);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (496, 'Nho Quan', 'Huyện', 41);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (497, 'Ninh Bình', 'Thành phố', 41);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (498, 'Tam Điệp', 'Thị xã', 41);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (499, 'Yên Khánh', 'Huyện', 41);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (500, 'Yên Mô', 'Huyện', 41);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (501, 'Cẩm Khê', 'Huyện', 42);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (502, 'Đoan Hùng', 'Huyện', 42);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (503, 'Hạ Hòa', 'Huyện', 42);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (504, 'Lâm Thao', 'Huyện', 42);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (505, 'Phù Ninh', 'Huyện', 42);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (506, 'Phú Thọ', 'Thị xã', 42);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (507, 'Tam Nông', 'Huyện', 42);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (508, 'Tân Sơn', 'Huyện', 42);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (509, 'Thanh Ba', 'Huyện', 42);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (510, 'Thanh Sơn', 'Huyện', 42);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (511, 'Thanh Thủy', 'Huyện', 42);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (512, 'Việt Trì', 'Thành phố', 42);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (513, 'Yên Lập', 'Huyện', 42);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (514, 'Bác Ái', 'Huyện', 43);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (515, 'Ninh Hải', 'Huyện', 43);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (516, 'Ninh Phước', 'Huyện', 43);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (517, 'Ninh Sơn', 'Huyện', 43);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (518, 'Phan Rang - Tháp Chàm', 'Thành phố', 43);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (519, 'Thuận Bắc', 'Huyện', 43);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (520, 'Thuận Nam', 'Huyện', 43);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (521, 'Đông Hòa', 'Huyện', 44);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (522, 'Đồng Xuân', 'Huyện', 44);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (523, 'Phú Hòa', 'Huyện', 44);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (524, 'Sơn Hòa', 'Huyện', 44);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (525, 'Sông Cầu', 'Thị xã', 44);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (526, 'Sông Hinh', 'Huyện', 44);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (527, 'Tây Hòa', 'Huyện', 44);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (528, 'Tuy An', 'Huyện', 44);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (529, 'Tuy Hòa', 'Thành phố', 44);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (530, 'Bình Lục', 'Huyện', 45);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (531, 'Duy Tiên', 'Huyện', 45);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (532, 'Kim Bảng', 'Huyện', 45);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (533, 'Lý Nhân', 'Huyện', 45);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (534, 'Phủ Lý', 'Thành phố', 45);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (535, 'Thanh Liêm', 'Huyện', 45);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (536, 'Cẩm Xuyên', 'Huyện', 46);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (537, 'Can Lộc', 'Huyện', 46);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (538, 'Đức Thọ', 'Huyện', 46);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (539, 'Hà Tĩnh', 'Thành phố', 46);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (540, 'Hồng Lĩnh', 'Thị xã', 46);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (541, 'Hương Khê', 'Huyện', 46);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (542, 'Hương Sơn', 'Huyện', 46);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (543, 'Kỳ Anh', 'Huyện', 46);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (544, 'Lộc Hà', 'Huyện', 46);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (545, 'Nghi Xuân', 'Huyện', 46);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (546, 'Thạch Hà', 'Huyện', 46);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (547, 'Vũ Quang', 'Huyện', 46);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (548, 'Cao Lãnh', 'Thành phố', 47);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (549, 'Châu Thành', 'Huyện', 47);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (550, 'Hồng Ngự', 'Thị xã', 47);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (551, 'Huyện Cao Lãnh', 'Huyện', 47);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (552, 'Huyện Hồng Ngự', 'Huyện', 47);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (553, 'Lai Vung', 'Huyện', 47);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (554, 'Lấp Vò', 'Huyện', 47);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (555, 'Sa Đéc', 'Thị xã', 47);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (556, 'Tam Nông', 'Huyện', 47);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (557, 'Tân Hồng', 'Huyện', 47);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (558, 'Thanh Bình', 'Huyện', 47);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (559, 'Tháp Mười', 'Huyện', 47);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (560, 'Châu Thành', 'Huyện', 48);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (561, 'Cù Lao Dung', 'Huyện', 48);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (562, 'Kế Sách', 'Huyện', 48);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (563, 'Long Phú', 'Huyện', 48);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (564, 'Mỹ Tú', 'Huyện', 48);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (565, 'Mỹ Xuyên', 'Huyện', 48);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (566, 'Ngã Năm', 'Huyện', 48);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (567, 'Sóc Trăng', 'Thành phố', 48);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (568, 'Thạnh Trị', 'Huyện', 48);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (569, 'Trần Đề', 'Huyện', 48);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (570, 'Vĩnh Châu', 'Huyện', 48);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (571, 'Đăk Glei', 'Huyện', 49);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (572, 'Đăk Hà', 'Huyện', 49);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (573, 'Đăk Tô', 'Huyện', 49);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (574, 'Ia H Drai', 'Huyện', 49);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (575, 'Kon Plông', 'Huyện', 49);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (576, 'Kon Rẫy', 'Huyện', 49);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (577, 'KonTum', 'Thành phố', 49);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (578, 'Ngọc Hồi', 'Huyện', 49);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (579, 'Sa Thầy', 'Huyện', 49);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (580, 'Tu Mơ Rông', 'Huyện', 49);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (581, 'Ba Đồn', 'Thị xã', 50);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (582, 'Bố Trạch', 'Huyện', 50);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (583, 'Đồng Hới', 'Thành phố', 50);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (584, 'Lệ Thủy', 'Huyện', 50);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (585, 'Minh Hóa', 'Huyện', 50);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (586, 'Quảng Ninh', 'Huyện', 50);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (587, 'Quảng Trạch', 'Huyện', 50);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (588, 'Tuyên Hóa', 'Huyện', 50);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (589, 'Cam Lộ', 'Huyện', 51);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (590, 'Đa Krông', 'Huyện', 51);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (591, 'Đảo Cồn cỏ', 'Huyện', 51);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (592, 'Đông Hà', 'Thành phố', 51);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (593, 'Gio Linh', 'Huyện', 51);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (594, 'Hải Lăng', 'Huyện', 51);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (595, 'Hướng Hóa', 'Huyện', 51);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (596, 'Quảng Trị', 'Thị xã', 51);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (597, 'Triệu Phong', 'Huyện', 51);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (598, 'Vĩnh Linh', 'Huyện', 51);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (599, 'Càng Long', 'Huyện', 52);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (600, 'Cầu Kè', 'Huyện', 52);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (601, 'Cầu Ngang', 'Huyện', 52);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (602, 'Châu Thành', 'Huyện', 52);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (603, 'Duyên Hải', 'Huyện', 52);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (604, 'Tiểu Cần', 'Huyện', 52);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (605, 'Trà Cú', 'Huyện', 52);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (606, 'Trà Vinh', 'Thành phố', 52);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (607, 'Châu Thành', 'Huyện', 53);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (608, 'Châu Thành A', 'Huyện', 53);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (609, 'Long Mỹ', 'Huyện', 53);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (610, 'Ngã Bảy', 'Thị xã', 53);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (611, 'Phụng Hiệp', 'Huyện', 53);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (612, 'Vị Thanh', 'Thành phố', 53);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (613, 'Vị Thủy', 'Huyện', 53);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (614, 'Bắc Yên', 'Huyện', 54);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (615, 'Mai Sơn', 'Huyện', 54);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (616, 'Mộc Châu', 'Huyện', 54);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (617, 'Mường La', 'Huyện', 54);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (618, 'Phù Yên', 'Huyện', 54);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (619, 'Quỳnh Nhai', 'Huyện', 54);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (620, 'Sơn La', 'Thành phố', 54);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (621, 'Sông Mã', 'Huyện', 54);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (622, 'Sốp Cộp', 'Huyện', 54);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (623, 'Thuận Châu', 'Huyện', 54);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (624, 'Vân Hồ', 'Huyện', 54);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (625, 'Yên Châu', 'Huyện', 54);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (626, 'Bạc Liêu', 'Thành phố', 55);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (627, 'Đông Hải', 'Huyện', 55);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (628, 'Giá Rai', 'Huyện', 55);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (629, 'Hòa Bình', 'Huyện', 55);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (630, 'Hồng Dân', 'Huyện', 55);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (631, 'Phước Long', 'Huyện', 55);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (632, 'Vĩnh Lợi', 'Huyện', 55);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (633, 'Lục Yên', 'Huyện', 56);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (634, 'Mù Cang Chải', 'Huyện', 56);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (635, 'Nghĩa Lộ', 'Thị xã', 56);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (636, 'Trạm Tấu', 'Huyện', 56);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (637, 'Trấn Yên', 'Huyện', 56);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (638, 'Văn Chấn', 'Huyện', 56);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (639, 'Văn Yên', 'Huyện', 56);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (640, 'Yên Bái', 'Thành phố', 56);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (641, 'Yên Bình', 'Huyện', 56);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (642, 'Chiêm Hóa', 'Huyện', 57);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (643, 'Hàm Yên', 'Huyện', 57);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (644, 'Lâm Bình', 'Huyện', 57);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (645, 'Na Hang', 'Huyện', 57);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (646, 'Sơn Dương', 'Huyện', 57);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (647, 'Tuyên Quang', 'Thành phố', 57);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (648, 'Yên Sơn', 'Huyện', 57);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (649, 'Điện Biên', 'Huyện', 58);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (650, 'Điện Biên Đông', 'Huyện', 58);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (651, 'Điện Biên Phủ', 'Thành phố', 58);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (652, 'Mường Ảng', 'Huyện', 58);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (653, 'Mường Chà', 'Huyện', 58);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (654, 'Mường Lay', 'Thị xã', 58);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (655, 'Mường Nhé', 'Huyện', 58);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (656, 'Nậm Pồ', 'Huyện', 58);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (657, 'Tủa Chùa', 'Huyện', 58);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (658, 'Tuần Giáo', 'Huyện', 58);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (659, 'Lai Châu', 'Thị xã', 59);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (660, 'Mường Tè', 'Huyện', 59);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (661, 'Nậm Nhùn', 'Huyện', 59);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (662, 'Phong Thổ', 'Huyện', 59);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (663, 'Sìn Hồ', 'Huyện', 59);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (664, 'Tam Đường', 'Huyện', 59);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (665, 'Tân Uyên', 'Huyện', 59);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (666, 'Than Uyên', 'Huyện', 59);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (667, 'Bắc Sơn', 'Huyện', 60);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (668, 'Bình Gia', 'Huyện', 60);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (669, 'Cao Lộc', 'Huyện', 60);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (670, 'Chi Lăng', 'Huyện', 60);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (671, 'Đình Lập', 'Huyện', 60);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (672, 'Hữu Lũng', 'Huyện', 60);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (673, 'Lạng Sơn', 'Thành phố', 60);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (674, 'Lộc Bình', 'Huyện', 60);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (675, 'Tràng Định', 'Huyện', 60);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (676, 'Văn Lãng', 'Huyện', 60);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (677, 'Văn Quan', 'Huyện', 60);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (678, 'Bắc Mê', 'Huyện', 61);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (679, 'Bắc Quang', 'Huyện', 61);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (680, 'Đồng Văn', 'Huyện', 61);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (681, 'Hà Giang', 'Thành phố', 61);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (682, 'Hoàng Su Phì', 'Huyện', 61);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (683, 'Mèo Vạc', 'Huyện', 61);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (684, 'Quản Bạ', 'Huyện', 61);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (685, 'Quang Bình', 'Huyện', 61);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (686, 'Vị Xuyên', 'Huyện', 61);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (687, 'Xín Mần', 'Huyện', 61);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (688, 'Yên Minh', 'Huyện', 61);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (689, 'Ba Bể', 'Huyện', 62);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (690, 'Bắc Kạn', 'Thị xã', 62);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (691, 'Bạch Thông', 'Huyện', 62);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (692, 'Chợ Đồn', 'Huyện', 62);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (693, 'Chợ Mới', 'Huyện', 62);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (694, 'Na Rì', 'Huyện', 62);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (695, 'Ngân Sơn', 'Huyện', 62);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (696, 'Pác Nặm', 'Huyện', 62);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (697, 'Bảo Lạc', 'Huyện', 63);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (698, 'Bảo Lâm', 'Huyện', 63);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (699, 'Cao Bằng', 'Thị xã', 63);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (700, 'Hạ Lang', 'Huyện', 63);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (701, 'Hà Quảng', 'Huyện', 63);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (702, 'Hòa An', 'Huyện', 63);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (703, 'Nguyên Bình', 'Huyện', 63);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (704, 'Phục Hòa', 'Huyện', 63);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (705, 'Quảng Uyên', 'Huyện', 63);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (706, 'Thạch An', 'Huyện', 63);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (707, 'Thông Nông', 'Huyện', 63);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (708, 'Trà Lĩnh', 'Huyện', 63);
INSERT INTO "District"("districtID", "districtName", prefix, "provinceID") VALUES (709, 'Trùng Khánh', 'Huyện', 63);