INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (1, 'SG', 'Hồ Chí Minh');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (2, 'HN', 'Hà Nội');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (3, 'DDN', 'Đà Nẵng');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (4, 'BD', 'Bình Dương');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (5, 'DNA', 'Đồng Nai');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (6, 'KH', 'Khánh Hòa');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (7, 'HP', 'Hải Phòng');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (8, 'LA', 'Long An');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (9, 'QNA', 'Quảng Nam');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (10, 'VT', 'Bà Rịa Vũng Tàu');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (11, 'DDL', 'Đắk Lắk');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (12, 'CT', 'Cần Thơ');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (13, 'BTH', 'Bình Thuận  ');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (14, 'LDD', 'Lâm Đồng');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (15, 'TTH', 'Thừa Thiên Huế');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (16, 'KG', 'Kiên Giang');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (17, 'BN', 'Bắc Ninh');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (18, 'QNI', 'Quảng Ninh');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (19, 'TH', 'Thanh Hóa');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (20, 'NA', 'Nghệ An');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (21, 'HD', 'Hải Dương');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (22, 'GL', 'Gia Lai');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (23, 'BP', 'Bình Phước');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (24, 'HY', 'Hưng Yên');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (25, 'BDD', 'Bình Định');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (26, 'TG', 'Tiền Giang');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (27, 'TB', 'Thái Bình');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (28, 'BG', 'Bắc Giang');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (29, 'HB', 'Hòa Bình');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (30, 'AG', 'An Giang');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (31, 'VP', 'Vĩnh Phúc');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (32, 'TNI', 'Tây Ninh');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (33, 'TN', 'Thái Nguyên');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (34, 'LCA', 'Lào Cai');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (35, 'NDD', 'Nam Định');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (36, 'QNG', 'Quảng Ngãi');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (37, 'BTR', 'Bến Tre');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (38, 'DNO', 'Đắk Nông');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (39, 'CM', 'Cà Mau');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (40, 'VL', 'Vĩnh Long');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (41, 'NB', 'Ninh Bình');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (42, 'PT', 'Phú Thọ');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (43, 'NT', 'Ninh Thuận');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (44, 'PY', 'Phú Yên');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (45, 'HNA', 'Hà Nam');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (46, 'HT', 'Hà Tĩnh');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (47, 'DDT', 'Đồng Tháp');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (48, 'ST', 'Sóc Trăng');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (49, 'KT', 'Kon Tum');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (50, 'QB', 'Quảng Bình');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (51, 'QT', 'Quảng Trị');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (52, 'TV', 'Trà Vinh');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (53, 'HGI', 'Hậu Giang');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (54, 'SL', 'Sơn La');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (55, 'BL', 'Bạc Liêu');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (56, 'YB', 'Yên Bái');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (57, 'TQ', 'Tuyên Quang');
INSERT INTO "Province"("provinceID", "code", "provinceName")VALUES (58, 'DDB', 'Điện Biên');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (59, 'LCH', 'Lai Châu');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (60, 'LS', 'Lạng Sơn');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (61, 'HG', 'Hà Giang');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (62, 'BK', 'Bắc Kạn');
INSERT INTO "Province"("provinceID", "code", "provinceName") VALUES (63, 'CB', 'Cao Bằng');